# Generated by Django 6.0.6 on 2026-07-01 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('HR', 'Human Resource'), ('PRODUCTION', 'Production'), ('ENGINEERING', 'Engineering'), ('QUALITY', 'Quality Control'), ('WAREHOUSE', 'Warehouse'), ('PURCHASING', 'Purchasing'), ('FINANCE', 'Finance'), ('IT', 'Information Technology'), ('GA', 'General Affairs'), ('MARKETING', 'Marketing')], max_length=30)),
                ('position', models.CharField(choices=[('STAFF', 'Staff'), ('OPERATOR', 'Operator'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('ENGINEER', 'Engineer'), ('TECHNICIAN', 'Technician'), ('ADMIN', 'Administrator'), ('INTERN', 'Intern'), ('LEADER', 'Leader')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
