# Generated by Django 6.0.6 on 2026-07-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='full_name',
        ),
    ]
