# Generated by Django 6.0.6 on 2026-07-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employeeprofile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
