# Generated by Django 6.0.6 on 2026-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
