# Generated by Django 6.0.6 on 2026-08-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeeprofile_nik'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Employee Online Booth', max_length=255)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('default_audience', models.CharField(choices=[('EMPLOYEE', 'All Employees'), ('PUBLIC', 'Public')], default='EMPLOYEE', max_length=20)),
                ('booth_per_page', models.PositiveIntegerField(default=10)),
                ('announcement_per_page', models.PositiveIntegerField(default=10)),
                ('featured_limit', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
