# Generated by Django 6.0.6 on 2026-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='show_featured_booth',
            field=models.BooleanField(default=True),
        ),
    ]
