# Generated by Django 6.0.6 on 2026-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_systemsetting_show_featured_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
