# Generated by Django 6.0.6 on 2026-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employeeprofile_phone_alter_employeeprofile_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
