# Generated by Django 6.0.6 on 2026-06-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BANNER', 'Banner'), ('VIDEO', 'Video'), ('PRESENTATION', 'Presentation'), ('DOCUMENT', 'Document'), ('MATERIAL', 'Material')], max_length=20)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='booths/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='booths/thumbnails/')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoothActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('COMPLETE', 'Complete')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booths.booth')),
            ],
        ),
    ]
