# Generated by Django 6.0.6 on 2026-06-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='booths/'),
        ),
    ]
