# Generated by Django 6.0.6 on 2026-06-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_alter_booth_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booth',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
