# Generated by Django 6.0.6 on 2026-06-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_booth_display_order_booth_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('PRESENTATION', 'Presentation'), ('ARTICLE', 'Article')], max_length=20)),
                ('file', models.FileField(upload_to='contents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='booths.booth')),
            ],
        ),
    ]
