# Generated by Django 6.0.6 on 2026-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_boothcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothactivity',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('OPEN', 'Open Resource'), ('COMPLETE', 'Complete')], max_length=20),
        ),
    ]
