# Generated by Django 6.0.6 on 2026-06-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0005_alter_boothactivity_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='file',
        ),
        migrations.RemoveField(
            model_name='booth',
            name='type',
        ),
    ]
