# Generated by Django 6.0.6 on 2026-06-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0006_remove_booth_file_remove_booth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothactivity',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='booths.boothcontent'),
        ),
    ]
