# Generated by Django 6.0.6 on 2026-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0007_boothactivity_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothcontent',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boothcontent',
            name='source_type',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('LINK', 'External Link')], default='UPLOAD', max_length=20),
        ),
        migrations.AddField(
            model_name='boothcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boothcontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contents/'),
        ),
    ]
