# Generated by Django 6.0.6 on 2026-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0008_boothcontent_external_url_boothcontent_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothcontent',
            name='target_audience',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('EMPLOYEE', 'All Employees'), ('HR', 'Human Resource'), ('PRODUCTION', 'Production'), ('ENGINEERING', 'Engineering'), ('QUALITY', 'Quality Control'), ('WAREHOUSE', 'Warehouse'), ('PURCHASING', 'Purchasing'), ('FINANCE', 'Finance'), ('IT', 'Information Technology'), ('GA', 'General Affairs'), ('MARKETING', 'Marketing')], default='EMPLOYEE', max_length=30),
        ),
    ]
