# Generated by Django 6.0.6 on 2026-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0009_boothcontent_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothcontent',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
