# Generated by Django 6.0.6 on 2026-08-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0010_boothcontent_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothactivity',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
