# Generated by Django 6.0.6 on 2026-06-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MEETING', 'Meeting'), ('SAFETY', 'Safety'), ('HR', 'HR'), ('EVENT', 'Event'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('target_audience', models.CharField(choices=[('ALL', 'All'), ('HR', 'HR'), ('PRODUCTION', 'Production'), ('ENGINEERING', 'Engineering')], default='ALL', max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
