# Generated by Django 6.0.6 on 2026-07-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(default='READ', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='announcements.announcement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user_email', 'action'), name='unique_announcement_activity')],
            },
        ),
    ]
