# Generated by Django 6.0.6 on 2026-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcementactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Employees'), ('HR', 'Human Resource'), ('PRODUCTION', 'Production'), ('ENGINEERING', 'Engineering'), ('QUALITY', 'Quality Control'), ('WAREHOUSE', 'Warehouse'), ('PURCHASING', 'Purchasing'), ('FINANCE', 'Finance'), ('IT', 'Information Technology'), ('GA', 'General Affairs'), ('MARKETING', 'Marketing')], default='ALL', max_length=50),
        ),
    ]
