# Generated by Django 6.0.6 on 2026-07-14 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_target_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='email_recipient_mode',
            field=models.CharField(choices=[('AUDIENCE', 'Target Audience'), ('SELECTED', 'Selected Employees')], default='AUDIENCE', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='selected_email_recipients',
            field=models.ManyToManyField(blank=True, related_name='announcement_email_recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
